services:
  server:
    image: novadityap/public-complaint-app-server
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    restart: always

  client:
    image: novadityap/public-complaint-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.production
    ports:
      - "5173:80"
    restart: always

