FROM php:8.4-cli-alpine

WORKDIR /var/www/html

RUN apk add --no-cache libzip-dev postgresql-dev \
    && docker-php-ext-install pdo_pgsql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./
RUN composer install --no-scripts --no-autoloader --no-dev

COPY . .
RUN composer dump-autoload --optimize --no-scripts

CMD ["php", "artisan", "serve", "--host=0.0.0.0"]